
package bullyingstop;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.*;
import java.sql.Connection;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;

public class BullyingStop extends javax.swing.JFrame {
    
   conexionMysql con = new conexionMysql();                                     //creamos la variable para la conexión
   Connection cn = con.conectar();
  
    
    public BullyingStop() {     
        
        initComponents();
        jPanel1.setVisible(false);                                         
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        mostrardatos();                                                         //creamos metodo
        limpiardatos();                                                         //creamos metodo
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtcurso = new javax.swing.JTextField();
        txtalias = new javax.swing.JTextField();
        txtcontraseña = new javax.swing.JTextField();
        btnregistrar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnseleccionar = new javax.swing.JButton();
        txtnomimagen = new javax.swing.JTextField();
        lblfoto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabledatos = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        lblimagen1 = new javax.swing.JLabel();
        lblmagen2 = new javax.swing.JLabel();
        btngeneratorPDF = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PANEL DE CONTROL");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STOPBULLYING ALUMNOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 253, 221));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese la siguiente información", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        txtnombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        txtid.setBorder(javax.swing.BorderFactory.createTitledBorder("Id"));
        txtid.setEnabled(false);

        txtapellidos.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellidos"));

        txtemail.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));

        txtcurso.setBorder(javax.swing.BorderFactory.createTitledBorder("Curso"));

        txtalias.setBorder(javax.swing.BorderFactory.createTitledBorder("Alias"));

        txtcontraseña.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));

        btnregistrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\luisr\\OneDrive\\Documentos\\NetBeansProjects\\BullyingStop\\imagen stopbullying\\registrar.png")); // NOI18N
        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        btnactualizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\luisr\\OneDrive\\Documentos\\NetBeansProjects\\BullyingStop\\imagen stopbullying\\actualizar.png")); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btneliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\luisr\\OneDrive\\Documentos\\NetBeansProjects\\BullyingStop\\imagen stopbullying\\eliminar.png")); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnseleccionar.setText("Seleccionar");
        btnseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseleccionarActionPerformed(evt);
            }
        });

        txtnomimagen.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen"));
        txtnomimagen.setMaximumSize(new java.awt.Dimension(64, 39));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtid)
                    .addComponent(lblfoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(txtemail)
                    .addComponent(txtcurso)
                    .addComponent(txtalias)
                    .addComponent(txtcontraseña)
                    .addComponent(txtnombre)
                    .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnregistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnactualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnomimagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnseleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblfoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23)))
                .addComponent(txtcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtalias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtnomimagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnseleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnregistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnactualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneliminar)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 253, 221));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Alumnos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        jtabledatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtabledatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabledatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabledatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabledatos);

        jTextField1.setBackground(new java.awt.Color(204, 253, 221));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setText("NO HAGAS A OTROS LO QUE NO TE GUSTARIA QUE HAGAN CONTIGO");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(204, 253, 221));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setText("NADIE TE PUEDE HACER SENTIR INFERIOR SIN TU CONSENTIMIENTO");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(204, 253, 221));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField3.setText("SI DENUNCIAS UN CASO DE ACOSO NO ERES UN CHIVATO, ERES UN VALIENTE");

        lblimagen1.setIcon(new javax.swing.ImageIcon("C:\\Users\\luisr\\OneDrive\\Documentos\\NetBeansProjects\\BullyingStop\\imagen stopbullying\\sbimg.jpg")); // NOI18N
        lblimagen1.setText("jLabel1");

        lblmagen2.setIcon(new javax.swing.ImageIcon("C:\\Users\\luisr\\OneDrive\\Documentos\\NetBeansProjects\\BullyingStop\\imagen stopbullying\\junta de andalucia educ.png")); // NOI18N
        lblmagen2.setText("jLabel2");

        btngeneratorPDF.setText("Generar PDF");
        btngeneratorPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngeneratorPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField1)
                    .addComponent(btngeneratorPDF))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblimagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblmagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btngeneratorPDF)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblimagen1))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblmagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleDescription("");

        jMenu1.setText("Usuarios");

        jMenuItem1.setText("Nuevo Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtabledatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabledatosMouseClicked
            // TODO add your handling code here:
            //
                                                                                //creamos este evento para redireccionarnos a la tabla
            int selectedRow = jtabledatos.getSelectedRow();                     //vamos a seleccionar la fila de la tabla
            System.out.println(selectedRow);
            if (selectedRow != -1) {
                
                Object id =  jtabledatos.getValueAt(selectedRow, 0);
                Object nombre = jtabledatos.getValueAt(selectedRow, 1);
                Object apellidos = jtabledatos.getValueAt(selectedRow, 2);
                Object email = jtabledatos.getValueAt(selectedRow, 3);
                Object curso = jtabledatos.getValueAt(selectedRow, 4);
                Object alias = jtabledatos.getValueAt(selectedRow, 5);
                Object contraseña = jtabledatos.getValueAt(selectedRow, 6);
                Object pathImagen = jtabledatos.getValueAt(selectedRow, 7);

                
               txtid.setText(id.toString());                                  //settexteamos todo lo que se recupere de la posicion 0 de la fila y asi sucesivamente 
               txtnombre.setText(nombre.toString());
               txtapellidos.setText(apellidos.toString());
               txtemail.setText(email.toString());
               txtcurso.setText(curso.toString());
               txtalias.setText(alias.toString());
               txtcontraseña.setText(contraseña.toString());
               txtnomimagen.setText(pathImagen.toString());
               

                Image foto = getToolkit().getImage(txtnomimagen.getText());
                foto = foto.getScaledInstance(48, 48, Image.SCALE_DEFAULT);
                lblfoto.setIcon(new ImageIcon(foto));
        
               
            }
    }//GEN-LAST:event_jtabledatosMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jPanel1.setVisible(true);
        jPanel2.setVisible(true);
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        try {
            PreparedStatement ps = cn.prepareStatement
            ("DELETE FROM usuarios WHERE usuarios.id ='"+txtid.getText()+"';");  //integramos nuestro comando para eliminar el usuario en la BBDD
            ps.execute();
            JOptionPane.showMessageDialog(null, "USUARIO ELIMINADO CORRECTAMENTE");  //nos va a mostrar un mensaje como que se ha eliminado el usuario
            mostrardatos();
            limpiardatos();

        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "HA HABIDO UN ERROR AL ELIMINAR" +e);   // o en su defecto dará un error
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handli ng code here:
        try {
            FileInputStream archivofoto;
            File nombre = new File(txtnomimagen.getText());
            try {
                archivofoto = new FileInputStream(nombre);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(BullyingStop.class.getName()).log(Level.SEVERE, null, ex);
            }
            PreparedStatement ps = cn.prepareStatement
            ("UPDATE usuarios SET nombre = ?,apellidos = ?,email = ?,curso = ?,alias = ?,contraseña = ?,nomimagen = ?,imagen = ? WHERE usuarios.id ='"+txtid.getText()+"';"); //integramos nuestro comando para actualizar el usuario en la BBDD
            ps.setString(1, txtnombre.getText());
            ps.setString(2, txtapellidos.getText());
            ps.setString(3, txtemail.getText());
            ps.setString(4, txtcurso.getText());
            ps.setString(5, txtalias.getText());
            ps.setString(6, txtcontraseña.getText());
            ps.setString(7, txtnomimagen.getText());
            ps.setString(8, lblfoto.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "DATOS ACTUALIZADOS CORRECTAMENTE");  //nos va a mostrar un mensaje como que se ha actualizado el usuario
            mostrardatos();
            limpiardatos();

        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR EL USUARIO" +e);    // o en su defecto dará un error
        }
        


    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        // TODO add your handling code here:
        String base64="";
        try {
            PreparedStatement ps = cn.prepareStatement ("INSERT INTO usuarios (nombre,apellidos,email,curso,alias,contraseña,nomimagen,imagen) VALUES (?,?,?,?,?,?,?,?)"); //integramos nuestro comando para registrar el usuario en la BBDD
            ps.setString(1, txtnombre.getText());                          //posicion en la cual el usuario va a registrar en la caja de texto y asi sucesivamente
            ps.setString(2, txtapellidos.getText());
            ps.setString(3, txtemail.getText());
            ps.setString(4, txtcurso.getText());
            ps.setString(5, txtalias.getText());
            ps.setString(6, txtcontraseña.getText());
            ps.setString(7, txtnomimagen.getText());
            
            try {
                File archivofoto = new File(txtnomimagen.getText());
                FileInputStream fileInput = new FileInputStream(archivofoto);
                byte[] file = new byte[(int) archivofoto.length()];
                fileInput.read(file);
                base64=Base64.getEncoder().encodeToString(file);
            } catch (Exception ex) {
                Logger.getLogger(BullyingStop.class.getName()).log(Level.SEVERE, null, ex);
            }
            ps.setString(8, base64);
            ps.execute();
            JOptionPane.showMessageDialog(null, "DATOS GUARDADOS CORRECTAMENTE");  //nos va a mostrar un mensaje como que se ha registrado el usuario
            mostrardatos();
            limpiardatos();

        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL GUARDAR USUARIO" +e);      // o en su defecto dará un error
        }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseleccionarActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG;*.JPEG)", "jpg","jpeg");
        JFileChooser archivo = new JFileChooser();
        archivo.addChoosableFileFilter(filtro);
        archivo.setDialogTitle("Abrir Archivo");
        File ruta = new File("D:/usuarios");
        archivo.setCurrentDirectory(ruta);
        int ventana = archivo.showOpenDialog(null);
        if(ventana == JFileChooser.APPROVE_OPTION)
        {
            File file = archivo.getSelectedFile();
            txtnomimagen.setText(String.valueOf(file));
            Image foto = getToolkit().getImage(txtnomimagen.getText());
            foto = foto.getScaledInstance(48, 48, Image.SCALE_DEFAULT);
            lblfoto.setIcon(new ImageIcon(foto));
        }
    }//GEN-LAST:event_btnseleccionarActionPerformed

    private void btngeneratorPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngeneratorPDFActionPerformed
        // TODO add your handling code here:
                generatePDF("usuario.pdf");
    }//GEN-LAST:event_btngeneratorPDFActionPerformed

    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BullyingStop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BullyingStop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BullyingStop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BullyingStop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BullyingStop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btngeneratorPDF;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnseleccionar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable jtabledatos;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JLabel lblimagen1;
    private javax.swing.JLabel lblmagen2;
    private javax.swing.JTextField txtalias;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcontraseña;
    private javax.swing.JTextField txtcurso;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnomimagen;
    // End of variables declaration//GEN-END:variables

    private void mostrardatos() {
        DefaultTableModel modelo=new DefaultTableModel();                       //modelo de tabla en el cual vamos a agregar columnas
        modelo.addColumn ("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Email");
        modelo.addColumn("Curso");
        modelo.addColumn("Alias");
        modelo.addColumn("Contraseña");
        modelo.addColumn("Imagen");
        jtabledatos.setModel(modelo);                                   //a la tabla se le asigna el modelo
        String consultasql="select*from usuarios"; //consulta sql para la BBDD
        String data[]=new String[9];                                            //string data para almacenar 7 indices
        
        Statement st;
        try {
            st=cn.createStatement();
            ResultSet rs=st.executeQuery(consultasql);
            while(rs.next()){                                                   //recorre los datos con un while
                data[0]=rs.getString(1);                                      //get string para ubicar nuestros datos
                data[1]=rs.getString(2);
                data[2]=rs.getString(3);
                data[3]=rs.getString(4);
                data[4]=rs.getString(5);
                data[5]=rs.getString(6);
                data[6]=rs.getString(7);
                data[7]=rs.getString(8);
                data[8]=rs.getString(9);
                modelo.addRow(data);
            }
        }catch (SQLException e) {
            System.out.println("Error al mostrar Datos " + e);
            }
        }

    private void limpiardatos() {
        txtid.setText("");                                                    //metodo para limpiar los datos del usuario en cada caja de texto
        txtnombre.setText("");
        txtapellidos.setText("");
        txtemail.setText("");
        txtcurso.setText("");
        txtalias.setText("");
        txtcontraseña.setText("");
        txtnomimagen.setText("");
        lblfoto.setText(""); 
    }
    
    public static void generatePDF(String filePath) {
        Document document = new Document();
  
        try {
            // Establecer la conexión a la base de datos
            conexionMysql con = new conexionMysql();                                     //creamos la variable para la conexión
            Connection cn = con.conectar();
            Statement st=cn.createStatement();
            // Consulta para obtener los usuarios
            String query = "SELECT * FROM usuarios";
            ResultSet resultSet = st.executeQuery(query);

            // Crear el documento PDF
            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();        
            
            // Agregar título al documento
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, BaseColor.BLACK);
            Paragraph title = new Paragraph("Usuarios Registrados", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            document.add(new Paragraph("\n"));
              
            
            // Agregar información de los usuarios al documento
            while (resultSet.next()) {
                String username = resultSet.getString("nombre");
                String apellidos = resultSet.getString("apellidos");
                String email = resultSet.getString("email");
                String curso = resultSet.getString("curso");
                String alias = resultSet.getString("alias");

                Paragraph userInfo = new Paragraph(
                        "Usuario: " + username + 
                                " Apellidos : " + apellidos +
                                ", Email: " + email +
                                ", Curso: " + curso +
                                ", Alias: " + alias);
                document.add(userInfo);
                document.add(new Paragraph("\n"));
            }

            // Cerrar el documento y liberar recursos
            document.close();
            resultSet.close();
            st.close();

            System.out.println("PDF generado exitosamente en: " + filePath);
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + filePath);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
    
